### ISSUE TITLE
Three undefined names

### ISSUE THREAD

**Issue by cclauss** [louisabraham/algnuth#2]
flake8 testing of https://github.com/louisabraham/algnuth on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./algnuth/polynom.py:216:26: F821 undefined name 'A'
    def __lt__(): return A.deg < B.deg
                         ^
./algnuth/polynom.py:216:34: F821 undefined name 'B'
    def __lt__(): return A.deg < B.deg
                                 ^
./algnuth/quadratic.py:125:9: F821 undefined name 'formes_reduites'
    l = formes_reduites(D)
        ^
3     F821 undefined name 'A'
```

**Comment by louisabraham** [comment]
Thanks, it is fixed now.

Do you want to add a .flake8 configuration file / a makefile rule to launch the checks?
I don't know very well the options of flake8…
